// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5YRVpOQGtRItYGVHiJAaKf_oLR_KdB4',
    appId: '1:293929116157:web:226196fb49f8aef793b994',
    messagingSenderId: '293929116157',
    projectId: 'shop-da808',
    authDomain: 'shop-da808.firebaseapp.com',
    storageBucket: 'shop-da808.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJ8DA9-uQ08ipQ9WePrF6SbObribhmnc',
    appId: '1:293929116157:android:4074fd47df23411393b994',
    messagingSenderId: '293929116157',
    projectId: 'shop-da808',
    storageBucket: 'shop-da808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaSqx-JSzSXElzcZ64fZ4Y2Zm8wWlUHw',
    appId: '1:293929116157:ios:750fd0075591f3cf93b994',
    messagingSenderId: '293929116157',
    projectId: 'shop-da808',
    storageBucket: 'shop-da808.appspot.com',
    iosBundleId: 'com.dominikgrosser.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbaSqx-JSzSXElzcZ64fZ4Y2Zm8wWlUHw',
    appId: '1:293929116157:ios:09ae7df2c6d5f80993b994',
    messagingSenderId: '293929116157',
    projectId: 'shop-da808',
    storageBucket: 'shop-da808.appspot.com',
    iosBundleId: 'com.dominikgrosser.shop.RunnerTests',
  );
}
